### ISSUE TITLE
RM4C and learning

### ISSUE THREAD

**Issue by chrismast** [t0mer/broadlinkmanager-docker#19]
He guys, just stumbled upon your docker image for the Broadlink Manager as the original app somehow does not support the RM4C anymore (?).
I was able to learn my TV and Mibox commands without issue (via MQTT implementation) whereas I did run into issues with my Samsung AC which somehow has different HEX codes every time I press a button (i.e. ON/OFF). Hence thought the Broadlink manager might be able to help in identifying the right codes.
I got it up and running (Proxmox LXC) and it seems my device is discovered whereas when I click Actions - Learn IR the bar just blinks quickly (showing shortly some bars progressing) whereas then disappearing and just showing "Error occurred while scanning, please try again"

The following appears in the log:

` 2021-01-09 11:20:38.081 | INFO     | __main__:<module>:515 - Broadllink Manager is up and running
broadlinkmanager    |  * Serving Flask app "broadlinkmanager" (lazy loading)
broadlinkmanager    |  * Environment: production
broadlinkmanager    |    WARNING: This is a development server. Do not use it in a production deployment.
broadlinkmanager    |    Use a production WSGI server instead.
broadlinkmanager    |  * Debug mode: on
broadlinkmanager    |  * Running on http://0.0.0.0:7020/ (Press CTRL+C to quit)
broadlinkmanager    |  * Restarting with stat
broadlinkmanager    | 2021-01-09 11:20:38.280 | INFO     | __main__:<module>:515 - Broadllink Manager is up and running
broadlinkmanager    |  * Debugger is active!
broadlinkmanager    |  * Debugger PIN: 240-589-367
broadlinkmanager    | 192.168.10.50 - - [09/Jan/2021 11:20:43] "GET / HTTP/1.1" 200 -
broadlinkmanager    | 2021-01-09 11:20:49.004 | INFO     | __main__:learnir:239 - Learning IR Code for device: 192.168.50.102
broadlinkmanager    | 2021-01-09 11:20:49.085 | INFO     | __main__:learnir:243 - Entering IR Learning Mode
broadlinkmanager    | /usr/local/lib/python3.6/dist-packages/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
broadlinkmanager    |   BrokenFilesystemWarning,
broadlinkmanager    | 192.168.10.50 - - [09/Jan/2021 11:20:49] "GET /ir/learn?type=0x6539&host=192.168.50.102&mac=a043b01582db HTTP/1.1" 500 -
broadlinkmanager    | Traceback (most recent call last):
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
broadlinkmanager    |     return self.wsgi_app(environ, start_response)
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app
broadlinkmanager    |     response = self.handle_exception(e)
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 272, in error_router
broadlinkmanager    |     return original_handler(e)
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception
broadlinkmanager    |     reraise(exc_type, exc_value, tb)
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
broadlinkmanager    |     raise value
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
broadlinkmanager    |     response = self.full_dispatch_request()
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
broadlinkmanager    |     rv = self.handle_user_exception(e)
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 272, in error_router
broadlinkmanager    |     return original_handler(e)
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
broadlinkmanager    |     reraise(exc_type, exc_value, tb)
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
broadlinkmanager    |     raise value
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
broadlinkmanager    |     rv = self.dispatch_request()
broadlinkmanager    |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
broadlinkmanager    |     return self.view_functions[rule.endpoint](**req.view_args)
broadlinkmanager    |   File "/opt/broadlinkmanager/broadlinkmanager.py", line 244, in learnir
broadlinkmanager    |     dev.enter_learning()
broadlinkmanager    | AttributeError: 'device' object has no attribute 'enter_learning'
broadlinkmanager    | 192.168.10.50 - - [09/Jan/2021 11:20:56] "GET / HTTP/1.1" 200 -
broadlinkmanager    | 192.168.10.50 - - [09/Jan/2021 11:20:57] "GET /img/broadlink.png HTTP/1.1" 200 -
broadlinkmanager    | 2021-01-09 11:20:59.595 | INFO     | __main__:learnir:239 - Learning IR Code for device: 192.168.50.102
broadlinkmanager    | 2021-01-09 11:20:59.625 | INFO     | __main__:learnir:243 - Entering IR Learning Mode
broadlinkmanager    | 192.168.10.50 - - [09/Jan/2021 11:20:59] "GET /ir/learn?type=0x6539&host=192.168.50.102&mac=a043b01582db HTTP/1.1" 500 -`

Any advice on how to fix above?

**Comment by t0mer** [comment]
Hi,
I just updated the broadlink manager to support 0x653c (RM4C).
please pull the latest image and try.
