### ISSUE TITLE
RF Issue: Can't learn single press

### ISSUE THREAD

**Issue by Stupco** [t0mer/broadlinkmanager-docker#3]
Hi There,

I tried getting this container working on docker on Windows but couldn't connect to the network.

As such, I created a VM for Home Assistant and installed via Portainer and was finally able to successfully connect.

It finds my RM2 Pro Plus_300 with no issues, and it discovers my remote on long press, however when I click "Status:   Click The Continue button" and press the button for a single click, it times out with the following error:
`Status:   To complete learning, single press the button you want to learn
_Error occurred while scanning, please try again_`

As such, trying multiple solutions to get BroadlinkManager working, it still doesn't seem to be able to learn RF codes as I was hoping. If I can get this working, it would solve a lot of pains for trying to automate my blinds! :)

I am using a DC1602 RF remote (provided by suppliers).

**Comment by Stupco** [comment]
Logs below:
`[I.P.ADD.R.ESS] - - [15/Jun/2020 02:46:12] "GET /rf/learn?type=0x27a9&host=192.168.1.142&mac=780f776317bc HTTP/1.1" 500 -


Traceback (most recent call last):


  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__


    return self.wsgi_app(environ, start_response)


  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2450, in wsgi_app


    response = self.handle_exception(e)


  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 272, in error_router


    return original_handler(e)


  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1867, in handle_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise


    raise value


  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app


    response = self.full_dispatch_request()


  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request


    rv = self.handle_user_exception(e)


  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 272, in error_router


    return original_handler(e)


  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise


    raise value


  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request


    rv = self.dispatch_request()


  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request


    return self.view_functions[rule.endpoint](**req.view_args)


  File "/opt/broadlinkmanager/broadlinkmanager.py", line 284, in sweep


    return jsonify('{"data":"' + data + '"}')


TypeError: must be str, not bytes


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:21] "GET /repeats HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:21] "GET /js/index.js HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:21] "GET /js/generator.js HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:21] "GET /js/pageActions.js HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:21] "GET /js/demo.js HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:21] "GET /repeats HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:47] "GET / HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:47] "GET / HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:52] "GET /rf/status HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:53] "GET /rf/status HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:54] "GET /rf/status HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:55] "GET /rf/status HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:56] "GET /rf/status HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:57] "GET /rf/status HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:57] "GET /rf/continue HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:58] "GET /rf/status HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:55:59] "GET /rf/status HTTP/1.1" 200 -


[I.P.ADD.R.ESS] - - [15/Jun/2020 02:56:00] "GET /rf/status HTTP/1.1" 200 -

 [I.P.ADD.R.ESS] - - [15/Jun/2020 02:56:00] "GET /rf/learn?type=0x27a9&host=192.168.1.142&mac=780f776317bc HTTP/1.1" 500 -
`

**Comment by Stupco** [comment]
And finally, to help debug, using the [Home Assistant broadlink.learn command ](https://www.home-assistant.io/integrations/broadlink/#learn-command) manual method, this is an example result of code generated by the remote:
`Received packet is: sgD8AKIzDBkMGQwZGA0MGRkNGA0LGgwZDBkYDRgOFw0MGQwZDBoMGQwZDBkMGQwZDBoLGRgOGA0YDRgNDBkMGQwZDBkMGgwZGA0MGRgNDBkYDQwZGAABI6EzDBkMGgsaFw0MGhcOGA0LGgwZDBkYDhcOGA0LGgsaDBkMGgsaCxoLGgsaCxoLGhgNGA0YDRgNDBkMGgsZDBoLGgwZGA0MGRgNDBkYDgsaGAABIaE0DBkLGgsaGA0MGRgNGA0MGgsaDBkYDRgNGA0MGQwZDBoLGgsaCxoLGgwZDBkMGRgOFw4XDhgNCxoLGgwZDBkLGwsaFw4LGhcOCxoXDgwZGAAF3AAAAAAAAAAAAAAAAA==`

**Comment by Stupco** [comment]
Fixed with commit 59f2f13493155f99f9daee8fa8fe6904fe030d1f
